[package]
name = "physics"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.1"
bevy_prototype_debug_lines = { version = "0.10.1", features = ["3d"] }
derive_setters = "0.1.5"
lerp = "0.4.0"
parry3d = "0.13.4"
rand = "0.8.5"

[profile.dev]
opt-level = 1
debug = true
